### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by gkze**
Just some basic corrections :)

### CODE REVIEW

**Comment by xjdrew** [comment]
I have delete all chinese words day before! thinks to @gkze anyway.

**Comment by gkze** [comment]
No problem! :+1:

**Comment by xjdrew** [comment]
@gkze do you use it?

**Comment by gkze** [comment]
Not yet, was going to start looking into it pretty soon once I had some more free time though!

**Comment by xjdrew** [comment]
ok, if find any bug please tell me!

**Pull request closed without merging**
